### ISSUE TITLE
interpolation with real images

### ISSUE THREAD

**Issue by gustn9609** [QY-H00/attention-interpolation-diffusion#1]
Hi,
I really enjoyed reading the PAID paper you recently posted in the archive
Thank you for your great work and code.

After looking at the paper and the code, I had some questions, so I wrote to you.
**Is it possible to do interpolation with real images?**
I ask because I tried to test it using DDIM inversion, but it didn't seem to work well.

Thank you.

**Comment by king159** [comment]
The current method is only designed to work on image generation progress. We are working on real image interpolation and the results shall be released one month later.
